POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "username": "test2",
    "email":"test2@email.com",
    "password": "test1"
}

###
GET http://localhost:5000/auth

###
POST http://localhost:5000/auth/signin
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}